[project]
name = "shield-factory"
authors = ["Anonymous Creator"]
description = "A decentralized milestone-based funding platform for creative projects"
telemetry = false
requirements = []

[contracts.shield-factory]
path = "contracts/shield-factory.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
